// Generated by Wrangler by running `wrangler types`

interface Env {
	scheduled: KVNamespace;
	meido: string;
	meidopath: string;
	API_TOKEN: string;
	account_id: string;
	project_name: string;
	email: string;
	elec: D1Database;
}
