name = "scheduled"
main = "src/index.ts"
compatibility_date = "2024-12-13"
minify = true
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = ["0 0 * * *", "0 7/8 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "scheduled"
database_id = "f237af9f-f89d-46cb-8079-9255e154c1b8"
